
-- Q1. What is the total revenue generated by male vs. female customers?

select Gender, sum( Purchase_amount) as Revenu
from customer 
group by Gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

select Customer_ID, Purchase_amount
from customer
where Discount_Applied='Yes' and Purchase_amount >= (select avg(Purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select Shipping_Type, round(avg(Purchase_amount),2) from customer
where Shipping_Type in ('Express','Standard')
group by Shipping_Type; 


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
 
select Subscription_Status,count(Customer_ID) as "total_peoples", 
round(avg(Purchase_amount),2) as "avg",
sum(Purchase_amount)  as "total_revenue"
from customer
group by Subscription_Status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;



-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;



-- Q8. What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select Subscription_Status, count(Customer_ID)
from customer
where Previous_Purchases>5
group by Subscription_Status;


-- Q10. What is the revenue contribution of each age group? 

select sum(Purchase_amount)as 'total_revenu', Age_group
from customer
group by Age_group
order by total_revenu desc;

